language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

# Dependencies
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install six

# Run tests
script: DJANGO_SETTINGS_MODULE=cleanerversion.settings.base python ./manage.py test versions
